services:
  mongo:
    image: mongo:7.0
    container_name: dbBasket
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - basket:/data/db
      - /home/debian/mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - basket-red
    environment:
    MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nasket-node
    container_name: basket-web
    restart: unless-stopped
    expose:
      - "8080"
    env_file:
      - .env
    networks:
      - basket-red
    depends_on:
      - mongo

  proxy:
    build: ./apache-config
    container_name: basket-proxy
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - basket-red
    depends_on:
      - web

    volumes:
      basket:

    networks:
      basket-red:
        name: basket-red